#!/bin/sh

printf "Arch Linux Installer\n"

printf "\n"

printf "! this process will delete entire of your disk.\n"

read -p "are you sure (y/n) : " confirm

if [ "$confirm" != "y" ]; then
	printf "Install aborted.\n"
	exit 1
fi

printf "Here we go...!\n"

parted -s /dev/sda -- mklabel gpt
parted -a optimal /dev/sda -- mkpart fat32 0% 1024M
parted -a optimal /dev/sda -- mkpart ext4 1024M 100%
parted -s /dev/sda -- set 1 esp on
parted -s /dev/sda -- name 1 efi
parted -s /dev/sda -- name 2 primary

mkfs.fat -F 32 /dev/sda1
mkfs.ext4 /dev/sda2

mount /dev/sda2 /mnt
mount /dev/sda1 /mnt/boot --mkdir

pacstrap /mnt base linux linux-firmware networkmanager

genfstab -U /mnt > /mnt/etc/fstab

printf "Install complete, system now mounted at /mnt.\n\n"

printf "/dev/sda2 mounted at /mnt\n"
printf "/dev/sda1 mounted at /mnt/boot\n"

printf "do the command : arch-chroot /mnt.\n"

printf "\n"
